# Generated by Django 5.0.3 on 2024-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="costumer_need", new_name="customer_need",
        ),
    ]
