# Generated by Django 5.0.3 on 2024-03-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_teams_team"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="facebook_link",),
        migrations.RemoveField(model_name="team", name="google_plus_link",),
        migrations.RemoveField(model_name="team", name="twitter_link",),
    ]
