# Generated by Django 5.0.3 on 2024-03-23 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_fuel_type_alter_car_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="description", field=ckeditor.fields.RichTextField(),
        ),
    ]
