# Generated by Django 5.0.3 on 2024-03-24 09:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="features",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=None, default=None, max_choices=None, min_choices=None
            ),
        ),
    ]
