# Generated by Django 5.0.3 on 2024-03-24 10:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="features",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=None, max_choices=None, max_length=100, min_choices=None
            ),
        ),
    ]
