# Generated by Django 5.0.3 on 2024-04-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0014_alter_car_features"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="features",),
        migrations.RemoveField(model_name="car", name="milage",),
    ]
