# Generated by Django 5.0.3 on 2024-04-06 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("your_name", models.CharField(max_length=100)),
                ("your_phone", models.IntegerField()),
                ("your_email", models.CharField(max_length=100)),
                ("your_address", models.CharField(max_length=100)),
                ("your_schedule", models.CharField(max_length=100)),
                ("your_day", models.CharField(max_length=100)),
                ("your_car", models.CharField(max_length=100)),
                ("your_message", models.TextField()),
                ("user_id", models.IntegerField(blank=True)),
                (
                    "create_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
