# Generated by Django 5.0.3 on 2024-04-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="car_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
